const DELETE_ITEM:string = "DELETE ITEM";
const AUMENTA_QTY:string = "ADD QTY";
const DIMINUISCI_QTY:string = "DIM QTY";
const SVUOTA_CARRELLO:string = "REMOVE ALL";
const COSTO_TOTALE:string = "SOMMA";
const CONTATORE:string = "CONTATORE";
const DATA_FETCHING_STARTED:string = "DATA_FETCHING_STARTED";
const DATA_FETCHING_FAILED:string = "DATA_FETCHING_FAILED";
const DATA_FETCHING_SUCCESS:string = "DATA_FETCHING_SUCCESS";

export {
  DATA_FETCHING_STARTED,
  DATA_FETCHING_FAILED,
  DATA_FETCHING_SUCCESS,
  DELETE_ITEM,
  AUMENTA_QTY,
  DIMINUISCI_QTY,
  SVUOTA_CARRELLO,
  CONTATORE,
  COSTO_TOTALE,
};
